### ISSUE TITLE
What's the correct type mapping for use with EFCore?

### ISSUE THREAD

**Issue by CharlieDigital** [pgvector/pgvector-dotnet#1]
I'm able to get it working correctly with Dapper but so far, no luck with EFCore.

In `OnModelCreating`, I have the following conversion registered:

```cs
modelBuilder
    .Entity<CategoryEmbedding>()
    .Property(e => e.Embedding) // This property is a Vector
    .HasConversion(
        v => v.ToArray(),
        v => new(v));

// Elsewhere
[Column(TypeName = "vector(1536)")]
public Vector? Embedding { get; set; } = new(Array.Empty<float>());
```

In my migration:

```cs
migrationBuilder.Sql("CREATE EXTENSION vector");

migrationBuilder.AddColumn<float[]>(
    name: "embedding",
    table: "category_embeddings",
    type: "vector(1536)",
    nullable: true);
```

The default type it assigns is `byte[]` and I've manually changed it to `float[]`.  Neither work correctly.

The error as reported by Postgres when using `float[]`:

```
ERROR:  column "embedding" is of type vector but expression is of type bytea at character 167
HINT:  You will need to rewrite or cast the expression.
STATEMENT:  INSERT INTO category_embeddings (id, active, category, created_by, created_utc, embedding, name, update_context, updated_by, updated_utc)
 	VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
```

The error as reported by Postgres when using `string`:

```
ERROR:  column "embedding" is of type vector but expression is of type character varying at character 167
HINT:  You will need to rewrite or cast the expression.
STATEMENT:  INSERT INTO category_embeddings (id, active, category, created_by, created_utc, embedding, name, update_context, updated_by, updated_utc)
 	VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
```

Any tips on getting the correct mapping with EFCore?

----

Current planned workaround is to use `float[]` and then add a trigger that converts it to `vector` in the DB.  Then on writes, use `float[]` via EF Core.  On reads, use Dapper and query on the `vector` column.

**Comment by ankane** [comment]
Hi @CharlieDigital, I spent some time on this, but think it might need its own plugin. I'd recommend using `ExecuteSql` for inserts for now.

```csharp
var embedding = new Vector(new float[] { 1, 2, 3 });
ctx.Database.ExecuteSql($"INSERT INTO category_embeddings (embedding) VALUES ({embedding.ToString()}::vector)");
```

**Comment by CharlieDigital** [comment]
@ankane Thanks for going the extra mile; appreciate it.

**Comment by ankane** [comment]
No problem. Just added a `Pgvector.EntityFrameworkCore` package. It only supports the `Vector` type right now, but planning to add distance functions and index options at some point (#2).

**Comment by JadynWong** [comment]
I am using Pgvector.EntityFrameworkCore, but I am getting an error message: `System.InvalidCastException: Can't cast database type .<unknown> to Vector`.

I must configure the vector mapper at program startup using `NpgsqlConnection.GlobalTypeMapper.UseVector()`.

I am aware that NpgsqlDbContextOptionsBuilder.UseVector() can also be used for configuration, but it does not seem to be working.
https://github.com/npgsql/efcore.pg/issues/2562#issuecomment-1339795868
