### ISSUE TITLE
Port to Npgsql 8

### ISSUE THREAD

**Issue by roji** [pgvector/pgvector-dotnet#11]
I'm filing this placeholder issue since we're planning a big overhaul of the Npgsql type handler system for 8.0; when that lands, I can take care of doing the necessary porting to make pgvector-dotnet compatible with the new system.

**Comment by ankane** [comment]
Hi @roji, this is captured in the `npgsql8` branch and #2, but can reopen if there's more to discuss.

**Comment by roji** [comment]
@ankane Npgsql and Npgsql.EntityFrameworkCore.PostgreSQL 8.0.0-rc.2 will be out in a few days; this will be the version with the more-or-less finalized new plugin model in Npgsql, which is fully compatible with NativeAOT/trimming and has many other improvements.

I plan to do the work to modify pgvector to run with this new version soon after rc2 releases. I can push my changes to the npgsql8-v2 branch, though it seems a bit out of date; can you rebase/merge it with master?

Once we merge the new support, I'm hoping you'll be able to publish a preview release for that branch, so that users (and us) can use pgvector with the 8.0 bits.

/cc @stephentoub
