### ISSUE TITLE
Fail to connection to Postgres 12

### ISSUE THREAD

**Issue by elparzival** [pgvector/pgvector-dotnet#16]
System.TypeLoadException: 'Method 'Create' in type 'Pgvector.Npgsql.VectorTypeHandlerResolverFactory' from assembly 'Pgvector, Version=0.1.3.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.'

**Comment by ankane** [comment]
Hi @elparzival, can you share a minimal example to reproduce?

**Comment by elparzival** [comment]
Hola amigo!

I am using Postgres 12.16-1
![image](https://github.com/pgvector/pgvector-dotnet/assets/4420742/0d18ac45-788c-41dd-897f-88818b3d040c)

in error occurs when entering the instruction "dataSourceBuilder.UseVector();"
![image](https://github.com/pgvector/pgvector-dotnet/assets/4420742/0045c74b-fc50-4e1a-87c0-fd8c48c4cbae)

**Comment by ankane** [comment]
Thanks @elparzival. Unfortunately, I'm not able to reproduce. What versions of .NET, Npgsql, and Dapper are you on?

**Comment by elparzival** [comment]
Net6,
dapper 2.0.151,
Npgsql 8.0

Will it be for my version of dapper or Npgsql?

**Comment by ankane** [comment]
Npgsql 8 support isn't released yet since it's still in preview (`npgsql8-v2` branch).

**Comment by elparzival** [comment]
Ok, I'll try to download my version, try again and give you feedback, thanks.
