### ISSUE TITLE
Insert CREATE EXTENSION call in EnsureCreatedAsync

### ISSUE THREAD

**Issue by shravan2x** [pgvector/pgvector-dotnet#17]
Currently, EnsureCreatedAsync doesn't call `CREATE EXTENSION vector;`. So the create script fails to run if any tables have a vector column.

Could the create extension call be injected into EnsureCreatedAsync?

**Comment by ankane** [comment]
Hi @shravan2x, you can use `HasPostgresExtension` for this.

```csharp
protected override void OnModelCreating(ModelBuilder modelBuilder)
{
    modelBuilder.HasPostgresExtension("vector");
}
```

**Comment by ankane** [comment]
Added to the readme in the commit above
