### ISSUE TITLE
How to return values greater than the specified similarity

### ISSUE THREAD

**Issue by qq312888991** [pgvector/pgvector-dotnet#20]
Code:
```
float[]? em = _chatApiService.ToEmbedding(text);
if (em!=null)
{
    int limit = 3;
    double score = 0.52;
    var vertor = new Vector(em);
    var list = await _pgVertorContext.KnowledgeBases.FromSql($"SELECT * FROM knowledge_base WHERE user_id ='{_userManager.user_id}' and vector_value <-> '{vertor}' >{score} ").ToListAsync();
    return list;
}
```

Why does this SQL statement report an exception：
![image](https://github.com/pgvector/pgvector-dotnet/assets/4046072/b589e846-e12c-4ad1-a04c-6aa5d5499488)

**Comment by ankane** [comment]
Hi @qq312888991, there shouldn't be single quotes around variables.

**Comment by qq312888991** [comment]
> Hi @qq312888991, there shouldn't be single quotes around variables.

thank!

**Comment by ankane** [comment]
No problem. Also, `<->` returns the distance (rather than the similarity), so you'll want to use `< {distance}` rather than `> {score}` to return the nearest vectors.

**Comment by qq312888991** [comment]
> No problem. Also, `<->` returns the distance (rather than the similarity), so you'll want to use `< {distance}` rather than `> {score}` to return the nearest vectors.没关系。此外， `<->` 返回距离（而不是相似性），因此您需要使用 `< {distance}` 而不是 `> {score}` 返回最近的向量。

Thanks again，I also discovered this issue during subsequent testing.
