### ISSUE TITLE
How to get the distance and score from a EF Core call?

### ISSUE THREAD

**Issue by Aspyryan** [pgvector/pgvector-dotnet#23]
I have code like this:
```c#
public async Task<List<DocumentEmbedding>> OrderBy(Vector embedding, int take = 5, List<string>? includes = null)
{
	using (var ctx = new ChatbotContext(CtxOptions))
	{
		var q = ctx.DocumentEmbedding.AsQueryable();
		if (includes != null)
			foreach (var include in includes) q = q.Include(include);

		return await q.OrderBy(x => x.Embedding!.L2Distance(embedding)).Take(take).ToListAsync();
	}
}
```

But I would also like to include the distance and score generated by the distance function. How would I do this, no reference in the docs for it?

**Comment by ankane** [comment]
Hi @Aspyryan, added an example in the commit above.

**Comment by Aspyryan** [comment]
Yes I saw it thank you alot!

**Comment by Aspyryan** [comment]
@ankane What is the best way to get this distance, filter and order all on the database side? Whenever I use the following code, I get trown an error because it cannot create an SQL query for the WithDistance class since it's not a database object. Should I use raw SQL for this or is there another workaround?

```c#
var result = q
	.Select(x => new WithDistance<DocumentEmbedding>(
		x.Embedding!.L2Distance(embedding),
		x
	))
	.Where(x => x.Distance < 0.6)
	.OrderBy(x => x.Distance)
	.Take(take)
	.ToList();

public class WithDistance<T>
{
	public double Distance { get; set; }
	public T Value { get; set; }

	public WithDistance(double distance, T value)
	{
		Distance = distance;
		Value = value;
	}
}
```

The WithDistance<T> class:

**Comment by ankane** [comment]
Thank you both - improved the examples in the commit above.
