### ISSUE TITLE
EF: Add modelBuilder API to configure dimension

### ISSUE THREAD

**Issue by bricelam** [pgvector/pgvector-dotnet#25]
In EF, the idiomatic way to configure blob or text column's max length is using `HasMaxLength`. It would be nice if you could also use this to configure a vector column's dimension.

In other words, I want this...

```cs
modelBuilder.Entity<MyEntity>()
    .Property(e => e.Vector).HasMaxLength(3);
```

...to produce this.

```sql
CREATE TABLE "MyEntity" (
    -- ...
    "Vector" vector(3),
    -- ...
);
```

### 🩹 Workaround

Today, you have to use `HasColumnType`.

```cs
modelBuilder.Entity<MyEntity>()
    .Property(e => e.Vector).HasColumnType("vector(3)");
```

**Comment by ankane** [comment]
Hi @bricelam, happy to include something like this if you want to submit a PR. I think ideally it'd be called `HasDimensions`, as `HasMaxLength` implies shorter vectors can be stored.

**Comment by ankane** [comment]
Cleaning up issues, but someone is welcome to submit a PR.
