### ISSUE TITLE
Update to Npsql 8 - Issue with TypeHandlerResolverFactory

### ISSUE THREAD

**Issue by Cotspheer** [pgvector/pgvector-dotnet#26]
**Describe the bug**
When using Microsoft.SemanticKernel.Connectors.Memory.Postgres 1.0.0-beta8 with Npsql 8.0 I'm not able to run the application. It fails with this exception:

```text
System.TypeLoadException: 'Could not load type 'Npgsql.Internal.TypeHandling.TypeHandlerResolverFactory' from assembly 'Npgsql, Version=8.0.0.0, Culture=neutral, PublicKeyToken=5d8b90d52f46fda7'.'
```
According to this [issue ](https://github.com/npgsql/npgsql/issues/5438) the TypeHandlerResolverFactory was removed but VectorExtensions.UseVector seems to require this.

Any chance that you can look into that? Without that I'm not able to use the semantic-kernel with Npsql 8 / .NET 8.

**Comment by ankane** [comment]
Hi @Cotspheer, just pushed version 0.2.0 of the `Pgvector` package, which supports Npgsql 8.

**Comment by Cotspheer** [comment]
Tahts awesome news! Thank you!

**Comment by redx177** [comment]
Can you add a `Pgvector.Dapper` 2.0  nuget package which references `Pgvector` 2.0?
