### ISSUE TITLE
Unable to create a 'DbContext' of type ''. The exception 'No suitable constructor was found for entity type 'Vector'.

### ISSUE THREAD

**Issue by doannamthai** [pgvector/pgvector-dotnet#27]
Hi guys,

I have been migrated to .NET 8:
![Screenshot 2023-11-28 at 4 53 09 PM](https://github.com/pgvector/pgvector-dotnet/assets/15958316/7258582e-80ab-43f7-9b41-785b35ac6acb)

But received this error when ran `dotnet ef dbcontext info`:

```
Unable to create a 'DbContext' of type ''. The exception 'No suitable constructor was found for entity type 'Vector'. The following constructors had parameters that could not be bound to properties of the entity type: 
    Cannot bind 'v' in 'Vector(ReadOnlyMemory<float> v)'
    Cannot bind 's' in 'Vector(string s)'
Note that only mapped properties can be bound to constructor parameters. Navigations to related entities, including references to owned types, cannot be bound.' was thrown while attempting to create an instance. For the different patterns supported at design time, see https://go.microsoft.com/fwlink/?linkid=851728
```

I already had the extension enabled and using Postgres 14.

Can you help please?

**Comment by ankane** [comment]
Hi @doannamthai, I'm not sure how to reproduce. What does the code that uses `Vector` look like?

**Comment by doannamthai** [comment]
Here is my schema
```
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Pgvector;

[Table("ChatMessage")]
public class ChatMessageDto
{
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    [Key]
    public string ChatMessageId { get; set; }
    
    [Column(TypeName = "vector(1536)"]
    public Vector? Embedding { get; set; }
}
```

```
public sealed class CoreFeaturesDbContext : DbContext
{
public DbSet<ChatMessageDto> ChatMessageDtos => Set<ChatMessageDto>();
}
```

**Comment by roji** [comment]
@doannamthai that's not a complete code sample, it's notably missing where you configure your context - you're likely missing UseVector there. If you do have UseVector() in your context configuration, then I think we'll need to see a fully runnable, minimal code sample (i.e. a console program).

**Comment by doannamthai** [comment]
I have updated my db factory to include useVector():

```
internal sealed class CoreFeaturesDbFactory : IDesignTimeDbContextFactory<CoreFeaturesDbContext>
{
    private const string DefaultConnectionString = "";

    public CoreFeaturesDbContext CreateDbContext(string[] args)
    {
        Log("Starting EF Core operation ...");

        var connectionString = Environment.GetEnvironmentVariable("SERVICE_CONNECTION_STRING");
        if (string.IsNullOrEmpty(connectionString))
        {
            Log("Environment variable 'SERVICE_CONNECTION_STRING' is not set. Will user default.");
            connectionString = DefaultConnectionString;
        }

        Log($"Running with DB Connection String: {connectionString}");
        var optionsBuilder = new DbContextOptionsBuilder<CoreFeaturesDbContext>();
        optionsBuilder.UseNpgsql(connectionString, b => b.UseVector());
        return new CoreFeaturesDbContext(optionsBuilder.Options);
    }

    private void Log(string message)
    {
        Console.WriteLine($"CoreFeaturesDbFactory: {message}");
    }
}
```

And new error thrown when I tried to run `dotnet db context info:`

`Unable to create a 'DbContext' of type ''. The exception 'Could not load type 'Pgvector.Npgsql.VectorExtensions' from assembly 'Pgvector, Version=0.2.0.0, Culture=neutral, PublicKeyToken=null'.' was thrown while attempting to create an instance. For the different patterns supported at design time, see https://go.microsoft.com/fwlink/?linkid=851728`

**Comment by roji** [comment]
@doannamthai I'm not sure what your program looks like or how you're reference pgvector, but I suggest you start with a simple, clean console app, make the minimal sample work from the documentation and work from there.

Otherwise, as I wrote, I'd really need a *fully runnable*, minimal code sample - including everything in the project (notably the csproj).

**Comment by ankane** [comment]
Cleaning up stale issues
