### ISSUE TITLE
Question: What's the "Add an approximate index" part for?

### ISSUE THREAD

**Issue by RonSijm** [pgvector/pgvector-dotnet#29]
Hey question, I curious what's the approximate index for, and is it optional, what's the difference?

The documentation says:

Add an approximate index

```csharp
protected override void OnModelCreating(ModelBuilder modelBuilder)
{
    modelBuilder.Entity<Item>()
        .HasIndex(i => i.Embedding)
        .HasMethod("ivfflat")
        .HasOperators("vector_l2_ops")
        .HasStorageParameter("lists", 100);
```
 // or

```csharp
    modelBuilder.Entity<Item>()
        .HasIndex(i => i.Embedding)
        .HasMethod("hnsw")
        .HasOperators("vector_l2_ops")
        .HasStorageParameter("m", 16)
        .HasStorageParameter("ef_construction", 64);
}
```

This part is mentioned after explaining how to use it - so I assume this is optional then, and not required for the core setup?

I'm a bit of a noob with pgvector, so sorry if this is a simple question, I'm just migrating from Pinecone, using a vector(1536).

Is there a difference between the two options? Which one would should I probably use with a vector(1536) for embed lookups?

**Comment by ankane** [comment]
Hi @RonSijm, check out [these docs](https://github.com/pgvector/pgvector#indexing) for more info on indexing (it is optional).

**Comment by RonSijm** [comment]
ok, thanks :)
