### ISSUE TITLE
42883: operator does not exist: vector <=> vector

### ISSUE THREAD

**Issue by jelianja** [pgvector/pgvector-dotnet#35]
I have issue with `CosineDistance` for finding the nearest neighbour. 
I created index in db, and I also have this part of code.
`modelBuilder.Entity<Item>()
    .HasIndex(i => i.Embedding)
    .HasMethod("ivfflat")
    .HasOperators("vector_cosine_ops")
    .HasStorageParameter("lists", 100);`

`CREATE INDEX "Embedding" ON "Item" USING ivfflat ("Embedding" vector_cosine_ops) WITH (lists='100')`

When it comes to this part, I get message that operator for cosine distance does not exist:

`var embedding = new Vector(vector);`
`var fvs = await _context.Item`
    `.OrderBy(x => x.Embedding.CosineDistance(embedding))`
    `.Take(5)`
    `.ToListAsync();`

I can execute cosine search directly from db, but when I try from .net I get this error, even I set up everything like in your example, I think.

**Comment by ankane** [comment]
Hi @jelianja, it may be a `search_path` issue. Make sure the schema where you installed the extension is in the `search_path` for your application.

```sql
SHOW search_path;
```

**Comment by jelianja** [comment]
I have just tried that, but it seems that problem is not solved. My schema is in search path. I can work with vectors and perform basic operation, load data from db in Vector class but when I want to perform <=> operation or any other similarity search, that error happens. I neither can't search vectors when I create function in db, and then try to call that function from code with FromSql() method, but I can execute query directly in db. If you have any other suggestions, I would appreciate that.

**Comment by ankane** [comment]
I haven't seen any reports of that exact error message before. I'd try to figure out what's different between the connection in your application and when you connect directly.
