### ISSUE TITLE
Update to Npsql 8 with `Pgvector.Dapper`

### ISSUE THREAD

**Issue by redx177** [pgvector/pgvector-dotnet#37]
There was an issue with Npgsql 8 and `Pgvector` 0.1 here: https://github.com/pgvector/pgvector-dotnet/issues/26
I am having the same issue with  `Pgvector.Dapper`. Can you create `Pgvector.Dapper` 0.2 which references `Pgvector` 0.2?

**Comment by ankane** [comment]
Hi @redx177, thanks for reporting! Just pushed a new release.

**Comment by redx177** [comment]
Awesome thank you. Right on time it seems: https://github.com/advisories/GHSA-x9vc-6hfv-hg8c
