### ISSUE TITLE
Unable to run using EF Core 8

### ISSUE THREAD

**Issue by MattParkerDev** [pgvector/pgvector-dotnet#4]
I get this error when trying to use this package with EF Core 8:

Unhandled exception. System.TypeLoadException: Method 'Create' in type 'Pgvector.Npgsql.VectorTypeHandlerResolverFactory' from assembly 'Pgvector, Version=0.1.1.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
   at Pgvector.Npgsql.VectorExtensions.UseVector(INpgsqlTypeMapper mapper)
   at Pgvector.EntityFrameworkCore.VectorDbContextOptionsBuilderExtensions.UseVector(NpgsqlDbContextOptionsBuilder optionsBuilder)

**Comment by ankane** [comment]
Hi @MattParkerDev, from the error, it seems like you're using a preview version of Npgsql 8. I've added support in the `npgsql8` branch, but waiting for the general release to merge / officially support.
