### ISSUE TITLE
When using EFCore, having a non public schema table that utilizes vector breaks the integration.

### ISSUE THREAD

**Issue by Pieeer1** [pgvector/pgvector-dotnet#40]
Steps to reproduce:
1. Create a standardized ef core dbcontext with the vector extensions.
2. Create a domain model that lives in a different schema than public 
3. Run a migration on this db context.
4. Attempt to do anything with that model (add or query or anything) and it should throw a not supported exception:
![image](https://github.com/pgvector/pgvector-dotnet/assets/11530364/fde85c69-af03-4b60-a62e-d8256c612f21)

I BELIEVE this is due to the fact that the data type just gets created in the public schema using ef core migrations. This is what that looks like on the database side:

![image](https://github.com/pgvector/pgvector-dotnet/assets/11530364/744cd55f-35fa-4b7f-b49f-9b6037c98f2b)

This fixes the issue in the Vector Type Info Resolver Factory:

![image](https://github.com/pgvector/pgvector-dotnet/assets/11530364/6f23e907-c53a-45e1-af3b-cdeb32de6d8a)

I will create a PR for this if this is the preferred way of solving this problem.

**Comment by roji** [comment]
@Pieeer1 are you changing your PostgreSQL `search_path` parameter, removing the `public` schema from it? EF should be simply generating SQL that references (unqualified) `public`, as long as you have an unmodified, default `search_path` that should just work.

Otherwise, can you put together a minimal, runnable console program that shows the problem?

**Comment by Pieeer1** [comment]
I have not changed the search path. 

Give me a little bit of time and I'll create a repository you can clone with the problem.

**Comment by Pieeer1** [comment]
Huh. As I was creating it I was completely unable to replicate the issue. I attempted multiple schemas, models, and setups to attempt to get it to break again. I was unable to get that to break. The ONLY difference I can see is that I am using an identity db context with all of the optional generic parameters? I am going to run some tests on that and see if that breaks it, but really odd stuff so far. I triple checked the search_path on both the test db and my actual db, and they are both the same. No clue why that is not functioning in the same way... 

Will send a repository in if I can replicate it, but overall this is very odd.

**Comment by Pieeer1** [comment]
I think I was doing some wacky stuff here I can't replicate. closing for now as this is working fine now. Unsure why that issue was really happening.
