### ISSUE TITLE
Bulk load example doesn't work

### ISSUE THREAD

**Issue by jon-wilda** [pgvector/pgvector-dotnet#41]
I am refactoring our application that inserts embedding records into our database from using straight inserts to bulk loads for hopefully some performance gains, and am not having any success. I copied the example in LoadingTests.cs verbatim to my application, and I receive the error `Writing values of 'Pgvector.Vector' is not supported for parameters having no NpgsqlDbType or DataTypeName. Try setting one of these values to the expected database type..`

If I specify the type as `vector` thusly `writer.Write(new Vector(embedding), "vector");` I get `Writing values of 'Pgvector.Vector' is not supported for parameters having DataTypeName 'public.vector'.`

I also tried `writer.Write(new Vector(embedding), "PgVector.vector");` and got `The data type name 'Pgvector.Vector' isn't present in your database. You may need to install an extension or upgrade to a newer version.`

I am using pgvector-dotnet version 0.2.0 and pgvector version 0.6.2.

**Comment by jon-wilda** [comment]
Sure thing - it's basically just that test example verbatim though.
[embedding-test.zip](https://github.com/user-attachments/files/15596643/embedding-test.zip)

**Comment by ankane** [comment]
Hi @jon-wilda, the example in the repo works fine. You can run it with:

```sh
TEST_LOADING=t dotnet test
```

fwiw, the first error message is the one you get if you comment out `dataSourceBuilder.UseVector();`.
