### ISSUE TITLE
Cannot read vector with Npgsql

### ISSUE THREAD

**Issue by fbenoit-coexya** [pgvector/pgvector-dotnet#42]
Hi,
I've been trying to read a vector with Npgsql (using `NpgsqlDataReader`) and the pgvector C# code, but to no avail.
I have checked that `AddVector()` **is** called on the `NpgsqlDataSourceBuilder` (after changing my code to use it since `NpgsqlConnection` no longer supports it), yet no matter what I do, I get this error:

> Reading as 'System.Object' is not supported for fields having DataTypeName 'public.vector'.

It seems the resolvers created by the `VectorTypeInfoResolverFactory` are never called (my breakpoints in them are never hit; the factory's Resolver property does hit my breakpoint otoh),

I even tried `GetStream()`, which gives me the same error.

**Comment by fbenoit-coexya** [comment]
I tried using **NpgsqlConnection.GlobalTypeMapper.UseVector()** instead of adding to the **NpgsqlDataSourceBuilder**, and it seems this time it worked, despite the "recommended" way not working.

**Comment by fbenoit-coexya** [comment]
Looks like it didn't like `connection.ConnectionString = connectionString;`.
Commenting it out gave me another error due to the data source being disposed before the connection is opened, but adding a `connection.Open()` to force opening before data source disposal seems to have fixed the problem.

**Comment by ankane** [comment]
Hi @fbenoit-coexya, I'm not sure the purpose of setting `ConnectionString` on the connection (instead of calling `dataSource.OpenConnection()`), but glad it's working now.

**Comment by fbenoit-coexya** [comment]
> Hi @fbenoit-coexya, I'm not sure the purpose of setting `ConnectionString` on the connection (instead of calling `dataSource.OpenConnection()`), but glad it's working now.

Well it was an artefact from when I thought I could build the data source ahead of the `CreateUnderlyingConnection()` method. But I learned the hard way that `Build()` throws if the builder is not supplied with a connection string, which forced me to put the whole building code in the method... and at the time I had not bothered to remove the `ConnectionString` assignment (since I had no idea it caused problems).
