### ISSUE TITLE
Brackets are missing for vector operators

### ISSUE THREAD

**Issue by llRandom** [pgvector/pgvector-dotnet#43]
I have a model with 2 vectors. The first one is should have higher weight. I'm trying to sort by sum of 2 distances but result query doesn't have brackets to wrap vector operators which gives invalid syntax.

Model definition
```
public class CompanyVector
{
    public int Id { get; set; }
    public required Vector PrimaryEmbedding { get; set; }
    public required Vector SecondaryEmbedding { get; set; }
}
```

Linq query
```
var vector = new[] { 1f, 2f, 3f };
EFContext.CompanyVectors.Select(i => i.PrimaryEmbedding.CosineDistance(new(vector)) + i.SecondaryEmbedding.CosineDistance(new(vector)));
```

Produced SQL
```
SELECT c.primary_embedding <=> @__p_0 + c.secondary_embedding <=> @__p_0
FROM company_vector AS c
```
ERROR:  operator does not exist: double precision <=> unknown

Expected SQL
```
SELECT (c.primary_embedding <=> @__p_0) + (c.secondary_embedding <=> @__p_0)
FROM company_vector AS c
```

The same problem happens if I use `OrderBy` linq method instead of `Select`

**Comment by roji** [comment]
Which version of EF and Npgsql.EntityFrameworkCore.PostgreSQL are you using?

**Comment by llRandom** [comment]
both 8.0.0

**Comment by ankane** [comment]
Hi @llRandom, this was fixed by @roji in Npgsql.EntityFrameworkCore.PostgreSQL 8.0.1 (https://github.com/npgsql/efcore.pg/issues/3072).

**Comment by llRandom** [comment]
Thanks @ankane! Upgrading Npgsql.EntityFrameworkCore.PostgreSQL worked
