### ISSUE TITLE
.net 6 support

### ISSUE THREAD

**Issue by idan-h** [pgvector/pgvector-dotnet#5]
Hey, I saw .net 6 is not supported, is there a reason for that? can I add support for .net 6?

**Comment by ankane** [comment]
Hi @idan-h, .NET 6 is supported (make sure you're on the latest release).

**Comment by tonykaralis** [comment]
Hi @ankane I have pulled this package and no NET 6 support. Am I missing something?

**Comment by idan-h** [comment]
> Hi @ankane I have pulled this package and no NET 6 support. Am I missing something?

I have just upgraded to .net 7 😆

I think it might be a nuget conf problem

**Comment by ankane** [comment]
Which package are you trying to use, and what error are you seeing?

**Comment by tonykaralis** [comment]
This is all i could find on Nuget. I can see more releases here but they are not on nuget.
<img width="689" alt="image" src="https://github.com/pgvector/pgvector-dotnet/assets/18276387/6519eaf5-57cf-4487-99db-eee6b100c233">

**Comment by sero323** [comment]
Im seeing the same error as well...
`error: NU1202: Package Pgvector 0.1.1 is not compatible with net6.0 (.NETCoreApp,Version=v6.0). Package Pgvector 0.1.1 supports: net7.0 (.NETCoreApp,Version=v7.0)`
even though it shows here that support was added....
https://github.com/pgvector/pgvector-dotnet/blob/master/src/Pgvector.EntityFrameworkCore/CHANGELOG.md

**Comment by ankane** [comment]
@sero323 For the `Pgvector` package, support was added in 0.1.2. https://github.com/pgvector/pgvector-dotnet/blob/master/src/Pgvector/CHANGELOG.md

You can also check this on Nuget:

- https://www.nuget.org/packages/Pgvector/0.1.2
- https://www.nuget.org/packages/Pgvector/0.1.1
