### ISSUE TITLE
Support for Cultures that uses separator of comma instead of dot.

### ISSUE THREAD

**Issue by Josephvs96** [pgvector/pgvector-dotnet#6]
Hi, 

I was facing a problem when trying to insert a vector with (1536 ) dimensions into a database and i kept getting the following exception 

`PostgresException: 22000: different vector dimensions 1536 and 3072
Npgsql.Internal.NpgsqlConnector.<ReadMessage>g__ReadMessageLong|234_0(NpgsqlConnector connector, bool async, DataRowLoadingMode dataRowLoadingMode, bool readingNotifications, bool isReadingPrependedMessage)` 

It turns out that because the default culture i have on my PC (Swedish) uses comma as decimal separator instead of dot, each floating number were considered two different numbers at the time of insert in the database. 

![image](https://github.com/pgvector/pgvector-dotnet/assets/76165094/104e7d78-583c-4474-a246-3903c7dc5f89)

Now i'm not really sure if there is some way to make this work on the database side of things. But my "fix" were to change the CurrentThread culture to be "en-GB". That worked but it might not be an option in the real word depending on how the UI is built and if we need to support different cultures.

One option could be to convert each floating point to a string with dot before joining the list with a comma. 

And yes btw thanks a lot for this awesome library 😄

**Comment by ankane** [comment]
Hi @Josephvs96, thanks for reporting. Can you share the code you're using for inserts? We can update the library to use `CultureInfo.InvariantCulture` for `ToString`, but statements should use the binary format.

**Comment by Josephvs96** [comment]
Absolutely, i'm using entity-framework to insert the data that is parsed from a csv file with the embeddings.
 
```csharp
            //We have to change the current culture in order to insert correct float values into the database
            Thread.CurrentThread.CurrentCulture = new System.Globalization.CultureInfo("en-GB");
            Thread.CurrentThread.CurrentUICulture = new System.Globalization.CultureInfo("en-GB");

            var config = new CsvConfiguration(CultureInfo.InvariantCulture)
            {
                PrepareHeaderForMatch = args => args.Header.ToLower(),
            };
            using (var reader = new StreamReader("org_embedded.csv"))
            using (var csv = new CsvReader(reader, config))
            {
                csv.Context.RegisterClassMap<DocumentCSVMap>();
                var records = csv.GetRecords<DocumentCSV>();

                foreach (var record in records)
                {
                    var doc = new Document()
                    {
                        DocumentText = record.Text,
                        Embedding = record.Embedding
                    };

                    _applicationDbContext.Documents.Add(doc);
                }
                await _applicationDbContext.SaveChangesAsync();
            }
``` 
Now actually the exact same problem is happening again when trying to get the nearest neighbours, that's where i'm getting the embedding value of en input text from the embedding OpenAI endpoint and just create a new Vector to send it to the database.

```csharp
 var embeddVector = new Vector(embed.Data.First().Embedding.Select(x => (float)x).ToArray());
 var items = await _applicationDbContext.Documents.FromSql($"""SELECT * FROM "Documents" ORDER BY "Embedding" <-> {embeddVector} LIMIT 5""").ToListAsync();
```

**Comment by ankane** [comment]
Still don't see why it'd be using the text representation, but can you try the commit above to see if that fixes it?

**Comment by Josephvs96** [comment]
That seems to do the trick! 

When debugging the `ToString()` method of the Vector it seems that it's being called from the interpolated string in the case of searching for nearest neighbours. And being called after `await _applicationDbContext.SaveChangesAsync(); ` when inserting data.

It could be that because `FromSql` is trying to actually wrap the objects sent in a `DbParameter` that might be converting them into string before sending the binary format? That might be the case when inserting data as well.  

https://learn.microsoft.com/en-us/ef/core/querying/sql-queries#passing-parameters

**Comment by ankane** [comment]
Thanks for checking. Just pushed Pgvector 0.1.3 with the fix. It looks like the text representation is always being used with Entity Framework Core (unlike Npgsql and Dapper). I don't see how to change it, but if someone else knows, happy to review a PR.

Thanks again for reporting!
