### ISSUE TITLE
Consider making Vector an immutable struct and renaming to PgVector

### ISSUE THREAD

**Issue by roji** [pgvector/pgvector-dotnet#8]
First off, I was pleasantly surprised to see the pg_vector .NET implementation, including Dapper and EF support (I'm the maintainer of Npgsql and the EF Core provider). Thanks for doing this work! I'll probably be submitting a few PRs/issues with suggestions to improve things.

First off, I'm wondering if there's any specific reason to require users to wrap their float[] with the Vector type provided by this library; is there any reason not to just map float[] directly? In Npgsql we try to abstain from introducing special types to map the PG ones unless necessary, and a simple .NET array seems to fit quite well here.

It could be said that mapping float[] to pg_vector's vector would conflict with the native mapping to a PG real[]; that also led me to wonder why pg_vector doesn't simply expose real[] to users in the first place, removing the need for any client-side support at all. But in any case, although mapping .NET float[] to vector would indeed hide the real[] mapping, users would still be able to easily send a real[] by specifying it explicitly (either via NpgsqlDbType or via DataTypeName).

On possible good reason to keep a dedicated type, is that we could add e.g. Distance methods on it, and then translate these with EF Core. This is similar to how the LTree support is done.

**Comment by roji** [comment]
One other thought - if you want to keep Vector as a distinct type, it's possible to make it a readonly struct instead of a class. It might also be a good idea to rename the type to PgVector, as Vector is a very generic name that could cause confusion with other types. .NET already has a built-in [Vector](https://learn.microsoft.com/en-us/dotnet/api/system.numerics.vector?view=net-7.0) type, which we could also in theory consider using (though that type is mainly used for vectorization intrinsics).

**Comment by ankane** [comment]
Hi @roji, thanks for Npgsql. As you mentioned, the `Vector` class was added to avoid conflicting with `real[]`.

The `vector` type in pgvector differs from `real[]` in that it enforces dimensions and doesn't allow NULL, NaN or infinite elements. It's possible to do this with a check constraint, but more friendly with a separate type:

```sql
CREATE TABLE items (embedding real[], CHECK(array_ndims(embedding) = 1 AND array_length(embedding, 1) = 3 AND array_position(embedding, NULL) IS NULL AND array_position(embedding, 'inf') IS NULL AND array_position(embedding, '-inf') IS NULL AND array_position(embedding, 'nan') IS NULL));
-- vs
CREATE TABLE items (embedding vector(3));
```

For class vs struct, a class seems like it's more appropriate based on [this criteria](https://learn.microsoft.com/en-us/dotnet/standard/design-guidelines/choosing-between-class-and-struct) (but may be missing something).

**Comment by roji** [comment]
Thanks for the explanation, makes sense.

> For class vs struct, a class seems like it's more appropriate based on [this criteria](https://learn.microsoft.com/en-us/dotnet/standard/design-guidelines/choosing-between-class-and-struct) (but may be missing something).

I do think it could make sense to make this a struct. The current Vector class is a simple wrapper around float[] (so just a single pointer), and is already itself immutable (the elements aren't).

I'd also go a step further and define value semantics by defining the Equals and the == operator to compare the encapsulated array reference (C# has records for that, but IIRC that's not available if you're targeting netstandard2.0).

**Comment by ankane** [comment]
The value equality change sounds good to me (can make them part of the 0.2.0 release when Npgsql 8 is released). I'd like to hold off on the struct change and renaming for now.

**Comment by roji** [comment]
Sounds good. I'm happy to continue doing work here - if you'd like, we can branch off and have main represent 0.2.0 (or vice versa) so the work doesn't have to wait; that of course depends on whether you have big work planned for versions prior to 0.2.0.

**Comment by roji** [comment]
@ankane I noticed there's an npgsql8 branch, let me know if you'd like me to submit a PR for this against that branch.

**Comment by ankane** [comment]
Thanks, that sounds good.

**Comment by roji** [comment]
Just submitted #15 to merge main into npgsql8 before I do this (though you may want to rebase instead).

BTW we have some pretty far-reaching changes in how the Npgsql (ADO-level) integration will be done for 8. I can take care of updating the plugin here when those changes land.

**Comment by ankane** [comment]
Cleaning up issues
